[package]
name = "pngme"
version = "0.1.0"
authors = ["xuyifan <xuyifan_frank@sjtu.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "^1.0.0"
clap = "^2.33.0"
structopt = "^0.3.20"
anyhow = "^1.0.33"